apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: apaches.apps.example.com
spec:
  group: apps.example.com
  names:
    kind: Apache
    listKind: ApacheList
    plural: apaches
    singular: apache
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
